import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
	    
		int numberOfTests = T;
		int sumOfChildren = 0;
		int amountOf2Children = 0;
		int amountOf3Children = 0;
		int amountOfMoreThan4Children = 0;


		for (int i = 0; i < numberOfTests; i++) {
			boolean isboy = false;
			boolean isgirl = false;
			int sum = 0;
			
			while (isboy == false || isgirl == false) {
				double rnd = generator.nextDouble();
				if (rnd < 0.5){
					isgirl = true;
					// System.out.print("g ");
				} else {
					isboy = true;
					// System.out.print("b ");
				}
				sum = sum + 1;
			}
			// System.out.println();

			sumOfChildren += sum;

			if (sum == 2) {
				amountOf2Children++;
			} else if (sum == 3) {
				amountOf3Children++;
			} else {
				amountOfMoreThan4Children++;
			}
		}
		// System.out.println();
		
		System.out.println("Average: " + ((double)sumOfChildren/numberOfTests) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + amountOf2Children);
		System.out.println("Number of families with 3 children: " + amountOf3Children);
		System.out.println("Number of families with 4 or more children: " + amountOfMoreThan4Children);

		if (amountOf2Children >= amountOf3Children && amountOf2Children >= amountOfMoreThan4Children) {
			System.out.println("The most common number of children is 2.");
		} else if (amountOf3Children >= amountOf2Children && amountOf3Children >= amountOfMoreThan4Children) {
			System.out.println("The most common number of children is 3.");
		} else {
			System.out.println("The most common number of children is 4 or more.");
		}
	}
}
